config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  root to: "home#index"
  resources :posts do
    member do
      get "publish"
      get "unpublish"
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/page.rb
class Page < ApplicationRecord
    has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :page

    validates_presence_of :title, :body

    def created_signature
        "Created at #{self.created_at.strftime("%Y-%m-%d")}"
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        @posts = Post.where(published: true).order(created_at: :DESC).limit(5)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    def index
        @posts = Post.all
        respond_to do |format|
          format.html
          format.json { render :json => @posts.to_json }
          format.xml { render :xml => @posts.as_json.to_xml }
        end
    end

    def show
      @post = Post.find(params[:id])
      respond_to do |format|
        format.html
        format.json { render :json => @post.to_json }
        format.xml { render :xml => @post.as_json.to_xml }
      end
    end

    def new
        @post = Post.new
    end

    def publish
      @post = Post.find(params[:id])
      @post.update(published: true)
      redirect_to posts_path
    end

    def unpublish
      @post = Post.find(params[:id])
      @post.update(published: false)
      redirect_to posts_path
    end

    def edit
        @post = Post.find(params[:id])
    end

    def create
        # Securite lors d'une assignation de masse, on filtre les paramètres authoriser avant de les envoyer au modèle qui gère la base de données
        # Voir fonction privé de ce controlleur
        #post_params = params.require(:post).permit(:title, :body)
        

        @post = Post.new(post_params)
        
        respond_to do |format|    
          if @post.save # Si la sauvegarde se passe bien, on redirige vers l'action index_5 pour rafraichir le formulaire
            format.html {redirect_to '/posts'}
          else
            format.html {render 'new' } # Si une erreur arrive, on l'affiche sur le formulaire d'origine
          end
          # Si utilisation en javascript
          format.json { render :json => @post.to_json }
          format.xml { render :xml => @post.as_json.to_xml }
        end
    end

    def update
        # Securite lors d'une assignation de masse, on filtre les paramètres authoriser avant de les envoyer au modèle qui gère la base de données
        # Voir fonction privé de ce controlleur
        #post_params = params.require(:post).permit(:title, :body)

        @post = Post.find(params[:id])        
        
        respond_to do |format|    
          if @post.update(post_params) # Si la sauvegarde se passe bien, on redirige vers l'action index_5 pour rafraichir le formulaire
            format.html {redirect_to '/posts'}
          else
            format.html {render 'edit' } # Si une erreur arrive, on l'affiche sur le formulaire d'origine
          end
          # Si utilisation en javascript
          format.json { render :json => @post.to_json }
          format.xml { render :xml => @post.as_json.to_xml }
        end
    end

    private
    def post_params
        params.require(:post).permit(:title, :body, :page_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1>Bienvenue sur mon blog!</h1>
<i>Vous avez <%= @posts.count %> visible</i>

<% @posts.each do |post| %>
<hr />
    <h2><%= post.title %></h2>
    <br />
    <p>
        <%= post.body[0..10] %>
    </p>
    <i><%= post.created_signature %></i>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Blog" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= link_to 'Accueil', root_path %>
    <%= link_to 'Mes posts', posts_path %>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<%= form_for(@post) do |f| %>
<%= f.label(:page) %>
  <%= @post.errors[:page].join('<br />') %>
  <br/>
  <%= f.select(:page_id, Page.all.collect{|p| [p.title, p.id]}) %>
  <br/>
  <%= f.label(:title) %>
  <%= @post.errors[:title].join('<br />') %>
  <br/>
  <%= f.text_field(:title) %>
  <br />
  <%= f.label(:body) %>
  <%= @post.errors[:body].join('<br />') %>
  <br/>
  <%= f.text_area(:body, rows: 20, cols:100) %>
  <br />
  <%= submit_tag("Modifier") %>
<% end %>

app/views/posts/index.html.erb
<h1>Mes posts (<%= link_to "New", new_post_path %>)</h1>
<br />
<table>
<% @posts.each do |post| %>
    <tr>
        <td><%= raw post.published ? "<b>Published!</b>" : "&nbsp;" %></td>
        <td>
            <%= post.title %> (<%= post.page ? post.page.title : ""%>)
        </td>
        <td>
            <% if post.published %>
                <%= link_to 'Unpublish', unpublish_post_path(post) %>
            <% else %>
                <%= link_to 'Publish', publish_post_path(post) %>
            <% end %>
            <%= link_to "edit", edit_post_path(post) %>
        </td>
    </tr>
<% end %>
</table>

app/views/posts/new.html.erb
<%= form_for(@post, method: "post") do |f| %>
  <%= f.label(:page) %>
  <%= @post.errors[:page].join('<br />') %>
  <br/>
  <%= f.select(:page_id,Page.all.collect{|p| [p.title, p.id]}) %>
  <br/>
  <%= f.label(:title) %>
  <%= @post.errors[:title].join('<br />') %>
  <br/>
  <%= f.text_field(:title) %>
  <br />
  <%= f.label(:body) %>
  <%= @post.errors[:body].join('<br />') %>
  <br/>
  <%= f.text_area(:body, rows: 20, cols:100) %>
  <br />
  <%= submit_tag("Ajouter") %>
<% end %>

app/views/posts/show.html.erb
<%= @post.title %><br />

<p>
    <%= @post.body %>
</p>

<%= @post.created_signature %>